### ISSUE TITLE
Create SingCellaR object directly from count matrix and annotation metadata files/objects

### ISSUE THREAD

**Issue by semmrich** [supatt-lab/SingCellaR#1]
Hello,
Please let me first congratulate you for this excellent software, and Kudos for the extensive documentation. I was wondering whether there would be a way to create the SingCellaR object from a count matrix in R. The function `load_gene_expression_from_a_file` seems to do that, but I do not have TARGET-Seq data but conventional 10X data. Some of my dataset sources do not come directly from cellranger outputs, and others come from de novo transcriptome alignments with the requirement to uniquefy gene names, which I do effectively with data.table before converting and loading as Seurat/SingleCellExperiment etc. Alternatively, is there a wrapper to convert SingleCellExperiment or Seurat Objects into SingCellaR?
Thank You,
Stephan

**Comment by supatt-lab** [comment]
Hi Stephan,
Yes, please see below the example.  
Hope this helps!

BW,
Supat

library(data.table)
library(Matrix)
library(SingleCellExperiment)
library(SingCellaR)

input_file<-"Your input matrix file" ##rows are genes and columns are cells.
sep="\t" ##separator
expM<-data.table::fread(input_file,sep=sep)
g.names<-as.data.frame(expM[,1])
g.names<-g.names[,1]
expM<-expM[,-c(1)]
expM.matrix<-as.matrix(expM)
rownames(expM.matrix)<-make.unique(g.names)
#######convert matrix to sparse matrix#####
Sp <- Matrix(expM.matrix,sparse = T)
sce<-SingleCellExperiment(assays = list(counts = Sp))
#######Create SingCellaR object############
#If you have Seurat object, you can export count matrix from Seurat as "sce" and then creat SingCellaR object as shown below.

Test_obj<-new("SingCellaR",sce)
process_cells_annotation(Test_obj,mitochondiral_genes_start_with="MT-")

#Please follow the standard pipeline found in the tutorial after this step.

**Comment by semmrich** [comment]
Super, I can just convert any "SingleCellExperiment" object into a "SingCellaR", it keeps dimreds and coldata and has its own slots for singcellar functions. Thank you very much, problem solved!
