### ISSUE TITLE
Couldn't install the package

### ISSUE THREAD

**Issue by Sophia409** [supatt-lab/SingCellaR#11]
Hi,
I can't install this package in R 4.1.5.
```
> devtools::install_github('supatt-lab/SingCellaR',ref='master', repos = BiocManager::repositories())
Downloading GitHub repo supatt-lab/SingCellaR@master
Error: Failed to install 'SingCellaR' from GitHub:
  Bioconductor version '3.12' requires R version '4.0'; use `BiocManager::install(version = '3.14')` with R version 4.1; see https://bioconductor.org/install
```
So I downgrade to R 4.0.4,but the installation still fails. The error is as follows:
```
* installing *source* package 'SingCellaR' ...
** using staged installation
** libs
"D:/soft ware/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"D:/soft ware/R-4.0.4/include" -DNDEBUG  -I'D:/soft ware/R-4.0.4/library/Rcpp/include' -I'D:/soft ware/R-4.0.4/library/RcppArmadillo/include' -I'D:/soft ware/R-4.0.4/library/RcppAnnoy/include'     -DARMA_64BIT_WORD -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c RcppExports.cpp -o RcppExports.o
"D:/soft ware/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"D:/soft ware/R-4.0.4/include" -DNDEBUG  -I'D:/soft ware/R-4.0.4/library/Rcpp/include' -I'D:/soft ware/R-4.0.4/library/RcppArmadillo/include' -I'D:/soft ware/R-4.0.4/library/RcppAnnoy/include'     -DARMA_64BIT_WORD -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c utils.cpp -o utils.o
D:/soft ware/rtools40/mingw64/bin/g++ -shared -s -static-libgcc -o SingCellaR.dll tmp.def RcppExports.o utils.o -LD:/personal data/Yuhong Zhang/Software/R-4.1.0/library/RcppParallel/lib/x64 -ltbb -ltbbmalloc -LD:/soft ware/R-4.0.4/bin/x64 -lR
g++.exe: error: data/Yuhong: No such file or directory
g++.exe: error: Zhang/Software/R-4.1.0/library/RcppParallel/lib/x64: No such file or directory
no DLL was created
ERROR: compilation failed for package 'SingCellaR'
* removing 'D:/soft ware/R-4.0.4/library/SingCellaR'
```
I couldn't find the solution. Could you give me some advice? Any suggestions would be appreciated.
Sophia

**Comment by supatt-lab** [comment]
Hi,

I have updated the package for R >=4.2. 
Please see the instruction from https://supatt-lab.github.io/SingCellaR.Doc/.

Best,
Supat

**Comment by boutrys** [comment]
Hello, 

I followed https://supatt-lab.github.io/SingCellaR.Doc/

But got stuck directly with 
install_github('supatt-lab/SingCellaR')

I have R.4.2.1, any ideas why ? 

Best, 

Here is what I got

── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\boutrys\AppData\Local\Temp\RtmpMRaLcZ\remotesb28366993d\supatt-lab-SingCellaR-e573341/DESCRIPTION' ... 
─  preparing 'SingCellaR': (919ms)
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (921ms)
─  checking for empty or unneeded directories
─  building 'SingCellaR_1.2.1.tar.gz'
   
* installing *source* package 'SingCellaR' ...
** using staged installation
** libs
g++  -std=gnu++11 -I"C:/Users/boutrys/ONEDRI~1/R/R-42~1.1/include" -DNDEBUG  -I'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/Rcpp/include' -I'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/RcppArmadillo/include' -I'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/RcppAnnoy/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DARMA_64BIT_WORD -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
g++  -std=gnu++11 -I"C:/Users/boutrys/ONEDRI~1/R/R-42~1.1/include" -DNDEBUG  -I'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/Rcpp/include' -I'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/RcppArmadillo/include' -I'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/RcppAnnoy/include'   -I"C:/rtools42/x86_64-w64-mingw32.static.posix/include"  -DARMA_64BIT_WORD -DRCPP_PARALLEL_USE_TBB=1   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c utils.cpp -o utils.o
In file included from utils.cpp:6:
nn_parallel.h:26:9: error: 'AnnoyIndexSingleThreadedBuildPolicy' does not name a type
   26 | typedef AnnoyIndexSingleThreadedBuildPolicy AnnoyIndexThreadedBuildPolicy;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
nn_parallel.h:29:20: error: 'Euclidean' does not name a type
   29 |   using Distance = Euclidean;
      |                    ^~~~~~~~~
nn_parallel.h:35:20: error: 'Angular' does not name a type
   35 |   using Distance = Angular;
      |                    ^~~~~~~
nn_parallel.h:41:20: error: 'Manhattan' does not name a type
   41 |   using Distance = Manhattan;
      |                    ^~~~~~~~~
nn_parallel.h:47:20: error: 'Hamming' does not name a type
   47 |   using Distance = Hamming;
      |                    ^~~~~~~
nn_parallel.h:62:3: error: 'AnnoyIndex' does not name a type
   62 |   AnnoyIndex<typename UwotAnnoyDistance::S, typename UwotAnnoyDistance::T,
      |   ^~~~~~~~~~
nn_parallel.h: In constructor 'NNWorker<UwotAnnoyDistance>::NNWorker(const string&, const std::vector<double>&, std::size_t, std::size_t, std::size_t)':
nn_parallel.h:70:65: error: class 'NNWorker<UwotAnnoyDistance>' does not have any field named 'index'
   70 |         idx(nrow * n_neighbors, -1), dists(nrow * n_neighbors), index(ncol) {
      |                                                                 ^~~~~
nn_parallel.h:71:5: error: 'index' was not declared in this scope; did you mean 'idx'?
   71 |     index.load(index_name.c_str());
      |     ^~~~~
      |     idx
nn_parallel.h: In destructor 'NNWorker<UwotAnnoyDistance>::~NNWorker()':
nn_parallel.h:75:5: error: 'index' was not declared in this scope; did you mean 'idx'?
   75 |     index.unload();
      |     ^~~~~
      |     idx
nn_parallel.h: In member function 'void NNWorker<UwotAnnoyDistance>::operator()(std::size_t, std::size_t)':
nn_parallel.h:86:7: error: 'index' was not declared in this scope; did you mean 'idx'?
   86 |       index.get_nns_by_vector(fv.data(), n_neighbors, search_k, &result,
      |       ^~~~~
      |       idx
make: *** [C:/Users/boutrys/ONEDRI~1/R/R-42~1.1/etc/x64/Makeconf:260: utils.o] Error 1
ERROR: compilation failed for package 'SingCellaR'
* removing 'C:/Users/boutrys/OneDrive - UCL/R/R-4.2.1/library/SingCellaR'
Warning message:
In i.p(...) :
  l'installation du package ‘C:/Users/boutrys/AppData/Local/Temp/RtmpMRaLcZ/fileb28334d632a/SingCellaR_1.2.1.tar.gz’ a eu un statut de sortie non nul

**Comment by supatt-lab** [comment]
Hi,

I just tested it on R.4.2.1, and it works fine for the installation. I
noted that I tested it on my MacBook! Not on Windows and Linux. I guess you
have a Windows system. I will try to find a Windows laptop to test it. It
seems to be something about your c compiler problem.
Probably try to update your c compiler. Let me know if that works.

Best,
Supat

**Comment by liu-ying-jun** [comment]
I am using a Macbook M2. But I have a similar error.

── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/3l/h153x2v96sb7w3q_2r2tldpm0000gs/T/RtmpMnPhAr/remotes108a22870a66/supatt-lab-SingCellaR-e573341/DESCRIPTION’ ...
─  preparing ‘SingCellaR’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘SingCellaR_1.2.1.tar.gz’
   
* installing *source* package ‘SingCellaR’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
using C++11
using SDK: ‘MacOSX13.3.sdk’
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include' -I/opt/R/arm64/include   -DARMA_64BIT_WORD -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include' -I/opt/R/arm64/include   -DARMA_64BIT_WORD -fPIC  -falign-functions=64 -Wall -g -O2  -c utils.cpp -o utils.o
In file included from utils.cpp:6:
./nn_parallel.h:26:9: error: unknown type name 'AnnoyIndexSingleThreadedBuildPolicy'; did you mean 'Annoy::AnnoyIndexSingleThreadedBuildPolicy'?
typedef AnnoyIndexSingleThreadedBuildPolicy AnnoyIndexThreadedBuildPolicy;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Annoy::AnnoyIndexSingleThreadedBuildPolicy
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include/annoylib.h:1425:7: note: 'Annoy::AnnoyIndexSingleThreadedBuildPolicy' declared here
class AnnoyIndexSingleThreadedBuildPolicy {
      ^
In file included from utils.cpp:6:
./nn_parallel.h:29:20: error: unknown type name 'Euclidean'; did you mean 'Annoy::Euclidean'?
  using Distance = Euclidean;
                   ^~~~~~~~~
                   Annoy::Euclidean
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include/annoylib.h:764:8: note: 'Annoy::Euclidean' declared here
struct Euclidean : Minkowski {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:35:20: error: unknown type name 'Angular'; did you mean 'Annoy::Angular'?
  using Distance = Angular;
                   ^~~~~~~
                   Annoy::Angular
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include/annoylib.h:440:8: note: 'Annoy::Angular' declared here
struct Angular : Base {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:41:20: error: unknown type name 'Manhattan'; did you mean 'Annoy::Manhattan'?
  using Distance = Manhattan;
                   ^~~~~~~~~
                   Annoy::Manhattan
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include/annoylib.h:795:8: note: 'Annoy::Manhattan' declared here
struct Manhattan : Minkowski {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:47:20: error: unknown type name 'Hamming'; did you mean 'Annoy::Hamming'?
  using Distance = Hamming;
                   ^~~~~~~
                   Annoy::Hamming
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include/annoylib.h:635:8: note: 'Annoy::Hamming' declared here
struct Hamming : Base {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:62:3: error: no template named 'AnnoyIndex'; did you mean 'Annoy::AnnoyIndex'?
  AnnoyIndex<typename UwotAnnoyDistance::S, typename UwotAnnoyDistance::T,
  ^~~~~~~~~~
  Annoy::AnnoyIndex
/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/RcppAnnoy/include/annoylib.h:848:9: note: 'Annoy::AnnoyIndex' declared here
  class AnnoyIndex : public AnnoyIndexInterface<S, T, 
        ^
6 errors generated.
make: *** [utils.o] Error 1
ERROR: compilation failed for package ‘SingCellaR’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/SingCellaR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/3l/h153x2v96sb7w3q_2r2tldpm0000gs/T//RtmpMnPhAr/file108a2f4a90fe/SingCellaR_1.2.1.tar.gz’ had non-zero exit status
