### ISSUE TITLE
Question about class object ‘SingCellaR_Int’ 

### ISSUE THREAD

**Issue by ArabicusPulp** [supatt-lab/SingCellaR#12]
Hi, thank you for providing such a convenient package for single cell analysis.I'm a student learning SingCellaR with the protocol on STAR Protocols (https://doi.org/10.1016/j.xpro.2022.101266). On step 14, I was trying to initialize the integrated SingCellaR class object ‘SingCellaR_Int’ with: 

> eFL <- new("SingCellaR_Int")

While RStudio warning me:

> Error in getClass(Class, where = topenv(parent.frame())) : 
  “SingCellaR_Int” is not a defined class

Could you help me with this problem?
Thank you in advance.
Wang

**Comment by supatt-lab** [comment]
Thanks for using SingCellaR! 

We removed 'SingCellaR_Int' class from the current version of SingCellaR.  
So, you can set up your object as below and then follow the analysis pipeline as described in the paper. 

eFL<-new("SingCellaR")

Hope this helps!
Best,
Supat
