### ISSUE TITLE
Problem in merging HSPC data

### ISSUE THREAD

**Issue by ArabicusPulp** [supatt-lab/SingCellaR#13]
Hello,
    Sorry for bothering you again, I have been learning SingCellaR these days while these errors happened:
    After merging HSPC data from eFL/FL/FBM/PBM/ABM, I was trying to add information with `mata.data.txt`(download form zenodo). However, the merged data of HSPC has 57416 objects while `mata.data.txt` has 57489 obs, then I tried to run `get_variable_genes_by_fitting_GLM_model` function:

> get_variable_genes_by_fitting_GLM_model(Human_HSPC,mean_expr_cutoff = 0.05,disp_zscore_cutoff = 0.05)
  Error in intI(j, n = x@Dim[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing

   I also tried to skip the step about adding information, but another error would occur when I used Supervised Harmony:

> SingCellaR::runSupervised_Harmony(Human_HSPC,
                                   covariates = c("batch","donor"),
                                   n.dims.use = 40,
                                   hcl.height.cutoff = 0.3,
                                   harmony.max.iter = 20,
                                   n.seed = 6)
Error in harmony::HarmonyMatrix(orig.pca, cell.meta, covariates, sigma = harmony.sigma,  : 
  must provide variables names (e.g. vars_use=‘stim’)
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Is there anything I can do to solve these problem? Or can I produce another mata.data.txt based on merged data?
    Thanks a lot for your assistance.
    Wang

**Comment by supatt-lab** [comment]
Hi,
Apologies for my slow reply. Would you download the Cell Ranger output files from this link: 
https://zenodo.org/record/5879071/files/cellranger_output.zip?download=1

Then extract the file and try to follow the R script below. You would have to install the current version of SingCellaR from this GitHub.

I hope this helps!
Best,
Supat

#####################
library(SingCellaR)
#####################
data_matrices_dir<-"cellranger_output/"

samples<-c("eFL1","eFL2","FL1","FL2","FBM1","FBM2","PBM1","PBM2","ABM1")
sample_names<-c("eFL_1","eFL_2","FL_1","FL_2","FBM_1","FBM_2","PBM_1","PBM_2","ABM_1")

for(i in 1:length(samples)){

  my_obj<-new("SingCellaR")
  my_obj@dir_path_10x_matrix<-paste(data_matrices_dir,samples[i],sep="/")
  my_obj@sample_uniq_id<-sample_names[i]
  load_matrices_from_cellranger(my_obj,cellranger.version = 3)
  process_cells_annotation(my_obj, mito_genes_start_with="MT-")
  filter_cells_and_genes(my_obj,min_UMIs=1000,
                         max_UMIs=100000,
                         min_detected_genes=500,
                         max_detected_genes=10000,
                         max_percent_mito=20,
                         genes_with_expressing_cells = 10,
                         isRemovedDoublets = FALSE)
  normalize_UMIs(my_obj, use.scaled.factor = T)
  get_variable_genes_by_fitting_GLM_model(my_obj,
                                          mean_expr_cutoff = 0.05,
                                          disp_zscore_cutoff = 0.05)
  out.file<-paste(samples[i],".rdata",sep="")
  save(my_obj, file=out.file)
}

####################################
Human_HSPC <- new("SingCellaR")
Human_HSPC@dir_path_SingCellR_object_files<-"."
Human_HSPC@SingCellR_object_files=c("eFL1.rdata","eFL2.rdata",
                                    "FL1.rdata","FL2.rdata",
                                    "FBM1.rdata","FBM2.rdata",
                                    "PBM1.rdata","PBM2.rdata",
                                    "ABM1.rdata")

preprocess_integration(Human_HSPC)
#####################################
#####################################
my_meta<-read.table("meta.data.txt",header=T)

Human_HSPC <-Human_HSPC[,my_meta$Cell]
Human_HSPC@meta.data<-my_meta
filter_cells_and_genes(Human_HSPC,
                       min_UMIs=1000,
                       max_UMIs=100000,
                       min_detected_genes=500,
                       max_detected_genes=10000,
                       max_percent_mito=20,
                       isRemovedDoublets = F)

normalize_UMIs(Human_HSPC, use.scaled.factor = T)
get_variable_genes_by_fitting_GLM_model(Human_HSPC,
                                        mean_expr_cutoff = 0.05,
                                        disp_zscore_cutoff = 0.05)

remove_unwanted_genes_from_variable_gene_set(Human_HSPC,
                                             gmt.file = "../Human_genesets/human.ribosomal-mitocondrial.genes.gmt",
                                             removed_gene_sets=c("Ribosomal_gene","Mitocondrial_gene"))
runPCA(Human_HSPC,
                   use.components = 100,
                   use.regressout.data = FALSE
                   
)
runHarmony(Human_HSPC,
                       covariates = c("batch","donor"),
                       n.dims.use = 40,
                       harmony.max.iter = 20,
                       n.seed = 6)

runUMAP(Human_HSPC,
                    useIntegrativeEmbeddings = T,
                    integrative_method = "harmony",
                    umap_method = "uwot",
                    n.dims.use = 40,
                    uwot.metric = "euclidean",
                    n.seed = 1)

plot_umap_label_by_multiple_gene_sets(Human_HSPC,gmt.file = "../Human_genesets/human.signature.genes.v1.gmt",
                                      show_gene_sets = c("Erythroid","Myeloid","Lymphoid","Megakaryocyte"),
                                      custom_color = c("red","cyan","orange","purple"),
                                      isNormalizedByHouseKeeping = F,
                                      point.size = 1)

**Comment by ArabicusPulp** [comment]
Your assistance are always helpful. Sadly I get stuck for contacting coronavirus patient recently and I would follow your advice as soon as possible.

Thank for your help!
