### ISSUE TITLE
Unable to unzip a file(Sample01_cellranger.zip) in SingCellaR_example_datasets.tar.gz

### ISSUE THREAD

**Issue by thecalab** [supatt-lab/SingCellaR#14]
Hi. Thanks for making this great package for single cell RNA-seq analysis. 
I'm trying to follow the excellent tutorial you provided. 
When I tried to follow integrative analysis from multiple samples, I found a specific file Sample01_cellranger.zip had a problem. I believe this file was compressed wrongly. 
I attached error message below.
Please check this issue.
Thank you.

`unzip Sample01_cellranger.zip`
Archive:  Sample01_cellranger.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of Sample01_cellranger.zip or
        Sample01_cellranger.zip.zip, and cannot find Sample01_cellranger.zip.ZIP, period.

**Comment by supatt-lab** [comment]
Hi,

You are right. Thank you for checking this issue. I have shared the updated datasets found in this link https://drive.google.com/drive/folders/1ko6XGu1OEoVdWDd2FdMlucx7IBK7Dpq0

Best,
Supat
