### ISSUE TITLE
Split by option?

### ISSUE THREAD

**Issue by gaiaandreoletti** [supatt-lab/SingCellaR#15]
Hi, 

I would like to split the UMAP split by status (e.g. controls on the right and healthy on the left).
How can i do this in SingCellaR? the split.by option does not work.

Thank you!
Gaia 

plot_umap_label_by_a_feature_of_interest(my_obj,feature = "status",point.size = 0.5, mark.feature = F, split.by = "status")

**Comment by supatt-lab** [comment]
Hi,

Apologies for my slow reply. 

I don’t think we have the “split.by” argument for this function in SingCellaR.
If you know which sample ids are control and cancer samples, then you can do:

plot_umap_label_by_selected_sampleID(my_obj,selected.sampleID = c(“control_1”,"control_2"),point.front.color = "cyan”)
plot_umap_label_by_selected_sampleID(my_obj,selected.sampleID = c(“cancer_1”,”cancer_2"),point.front.color = “red”)

Hope this helps!

Best,
Supat
