### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by LorenzoLF** [supatt-lab/SingCellaR#17]
Dear SingCellaR developers and community,

I am trying to install SingCellaR on R version 4.3.1 (macOS 11.7.8), but there seems to be a problem:

`install_github('supatt-lab/SingCellaR')
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo supatt-lab/SingCellaR@HEAD
Skipping 6 packages not available: AUCell, ComplexHeatmap, limma, fgsea, SummarizedExperiment, SingleCellExperiment
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────
   checking DESCRIPTION meta-information ...v/b39ypptx74dcdnp82rr3pmx80000gp/T/Rtmp5iZycl/remotes2bde57a0a5c9/supatt-lab-SingCellaR-e573341/DESCRIPTION’ ...
Installing package into ‘/Users/lorenzo/Library/R/x86_64/4.3/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SingCellaR’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 11.0.3 (clang-1103.0.32.59)’
using C++11
using SDK: ‘MacOSX10.15.sdk’
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include' -I/opt/R/x86_64/include   -DARMA_64BIT_WORD -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppArmadillo/include' -I'/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include' -I/opt/R/x86_64/include   -DARMA_64BIT_WORD -fPIC  -falign-functions=64 -Wall -g -O2  -c utils.cpp -o utils.o
In file included from utils.cpp:6:
./nn_parallel.h:26:9: error: unknown type name 'AnnoyIndexSingleThreadedBuildPolicy'; did you mean 'Annoy::AnnoyIndexSingleThreadedBuildPolicy'?
typedef AnnoyIndexSingleThreadedBuildPolicy AnnoyIndexThreadedBuildPolicy;
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Annoy::AnnoyIndexSingleThreadedBuildPolicy
/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include/annoylib.h:1425:7: note: 'Annoy::AnnoyIndexSingleThreadedBuildPolicy' declared here
class AnnoyIndexSingleThreadedBuildPolicy {
      ^
In file included from utils.cpp:6:
./nn_parallel.h:29:20: error: unknown type name 'Euclidean'; did you mean 'Annoy::Euclidean'?
  using Distance = Euclidean;
                   ^~~~~~~~~
                   Annoy::Euclidean
/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include/annoylib.h:764:8: note: 'Annoy::Euclidean' declared here
struct Euclidean : Minkowski {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:35:20: error: unknown type name 'Angular'; did you mean 'Annoy::Angular'?
  using Distance = Angular;
                   ^~~~~~~
                   Annoy::Angular
/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include/annoylib.h:440:8: note: 'Annoy::Angular' declared here
struct Angular : Base {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:41:20: error: unknown type name 'Manhattan'; did you mean 'Annoy::Manhattan'?
  using Distance = Manhattan;
                   ^~~~~~~~~
                   Annoy::Manhattan
/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include/annoylib.h:795:8: note: 'Annoy::Manhattan' declared here
struct Manhattan : Minkowski {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:47:20: error: unknown type name 'Hamming'; did you mean 'Annoy::Hamming'?
  using Distance = Hamming;
                   ^~~~~~~
                   Annoy::Hamming
/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include/annoylib.h:635:8: note: 'Annoy::Hamming' declared here
struct Hamming : Base {
       ^
In file included from utils.cpp:6:
./nn_parallel.h:62:3: error: no template named 'AnnoyIndex'; did you mean 'Annoy::AnnoyIndex'?
  AnnoyIndex<typename UwotAnnoyDistance::S, typename UwotAnnoyDistance::T,
  ^~~~~~~~~~
  Annoy::AnnoyIndex
/Library/Frameworks/R.framework/Versions/4.3-x86_64/Resources/library/RcppAnnoy/include/annoylib.h:848:9: note: 'Annoy::AnnoyIndex' declared here
  class AnnoyIndex : public AnnoyIndexInterface<S, T, 
        ^
6 errors generated.
make: *** [utils.o] Error 1
ERROR: compilation failed for package ‘SingCellaR’
* removing ‘/Users/lorenzo/Library/R/x86_64/4.3/library/SingCellaR’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/jv/b39ypptx74dcdnp82rr3pmx80000gp/T//Rtmp5iZycl/file2bde3494849a/SingCellaR_1.2.1.tar.gz’ had non-zero exit status`

Any help would be highly appreciated. I have tried to install it in 3 different computers and there have been installation problems in each of them.

Thank you very much.

**Comment by supatt-lab** [comment]
Thanks for reporting this! I just fixed the installation issue. 

Please try :
> library(devtools)
> install_github('supatt-lab/SingCellaR')

Let me know if you still have a problem.

Best,
Supat

**Comment by LorenzoLF** [comment]
It works perfectly now :)

Thank you very much for the fast reply and great work!

Best regards.
