### ISSUE TITLE
Datasets information

### ISSUE THREAD

**Issue by mdbabumiamssm** [supatt-lab/SingCellaR#18]
Hi Supat, 

Thank you for the great work. 

The google drive linked datasets had five 10x genomics output!
I believe, the dataset is from geo GSE131593 !
![image](https://github.com/supatt-lab/SingCellaR/assets/116982937/d58dcc2c-a784-44cc-bc02-84f4d5e56dbb)
Can you please share the following information: 
1. Sample Identity: Which sample belong to Healthy donor and Myelofibrosis group ?
2. Publication information  : Which publication this data belongs ?

it will be great help if you kindly share the information. 

best regards,
MD BABU MIA, PHD
Icahn School of Medicine at Mount Sinai

**Comment by supatt-lab** [comment]
Hi,

Please see "GSE144568" and https://pubmed.ncbi.nlm.nih.gov/32386542/ for more information.

Best,
Supat

**Comment by mdbabumiamssm** [comment]
Thanks. I was little confused as i couldn't find GSE131593 in the publication. 
Does first two sample are healthy donor and last three are MF ? 

Thanks

**Comment by supatt-lab** [comment]
Yes that is correct. Single-cell datasets were from this https://pubmed.ncbi.nlm.nih.gov/32386542/ paper.

Best,
Supat
