### ISSUE TITLE
Application Programming Interface(API) for SingCellaR

### ISSUE THREAD

**Issue by FionaMoon** [supatt-lab/SingCellaR#2]
Hello!
SingCellaR is a very convenient tool for scRNA-seq analysis and it helps me a lot.  But I use multiple tools for scRNA-seq analysis (Seurat / Scanpy ···) and  I find SingCellaR can only read one format of file with `load_matrices_from_cellranger( )` . I can't find any function in SingCellaR which allow me to input data such as **.csv / .h5ad / .mtx** 
I would highly appreciate your help on how to solve this issue.
Thank you for reading.
Fiona

**Comment by supatt-lab** [comment]
Hi Fiona,

Apologies for my slow response and thanks for using SingCellaR!

SingCellaR uses SingleCellExperiment to build its object.
So, if you can read in and transform a gene expression table  into the
‘mat’ matrix, you can simply build a SingCellaR object as shown in the
example below:

library(SingCellaR)
library(SingleCellExperiment)

sce<-SingleCellExperiment(assays = list(counts = mat))
SingCellaR_obj<-new("SingCellaR", sce)

Hope this helps!

BW,
Supat

**Comment by FionaMoon** [comment]
Thanks! 
You answer really inspired me. I make a summary for how to load different format files into SingCellaR. 

**For Seurat object**
` library(data.table)`
`library(Matrix)`
`library(SingleCellExperiment)`
`library(SingCellaR)`
`data <- read_rds("./Seurat.rds ")`
`class(data@assays$RNA@counts)`
`sce<-SingleCellExperiment(assays = list(counts = data@assays$RNA@counts))`
`Test_obj <-new("SingCellaR",sce)`
`Test_obj` # An object of class SingCellaR with a matrix of : 14045 genes across 24532 samples.
`process_cells_annotation(Test_obj,mito_genes_start_with="MT-")`
...

**For CSV** 
1. write a new function

```
library(SingCellaR)
wkdir = "./data/singlecell/hs/GSE149938_BM.PB"

data_matrices_dir<-paste(wkdir,"Seurat/read10x.rds", sep = "/")
BM = new("SingCellaR")
BM@dir_path_10x_matrix<-data_matrices_dir
BM@sample_uniq_id = "BM"

# 10x_matrix must save as rds/feather/Rdata ``` , which canbe load smoothly
# readRDS(data_matrices_dir)

load_matrix_from_csv = function (object,  SparseMatrix = TRUE) 
{
  objName <- deparse(substitute(object))
    if (!is(object, "SingCellaR")) {
    stop("Need to initialize the SingCellaR object")
  }
    data.dir <- object@dir_path_10x_matrix
    if (!file.exists(data.dir)) {
        stop("File of 10xMatrix provided does not exist")
    }
    if (SparseMatrix == TRUE) {
    mat = readRDS(data_matrices_dir)  
  }
    library(SingleCellExperiment)
    sce <- SingleCellExperiment(assays = list(counts = mat))
    if (class(object)[1] == "SingCellaR") {
      object <- new("SingCellaR", sce, dir_path_10x_matrix = data.dir, 
                    sample_uniq_id = object@sample_uniq_id)
    }
    else if (class(object)[1] == "SingCellaR_Int") {
      object <- new("SingCellaR_Int", sce, dir_path_10x_matrix = data.dir, 
                    sample_uniq_id = object@sample_uniq_id)
    }
    assign(objName, object, envir = parent.frame())
    invisible(1)
    print("The sparse matrix is created.")
}
load_matrix_from_csv(BM)
```
2. input csv
```
data <- fread("../data/control/orignal_counts.csv")
data[1:4,1:4]
#               V1 AAACATACATTTCC.1 AAACATACCAGAAA.1 AAACATACCATGCA.1
# 1:    AL627309.1                0                0                0
# 2: RP11-206L10.2                0                0                0
# 3:     LINC00115                0                0                0
# 4:         NOC2L                0                0                0

table(unique(data[,1])==F)
# FALSE 
# 13530 

exp <- as.data.frame(data)
rownames(exp) <- exp$V1
exp <- exp[,-1]
exp[1:4,1:4]

#######convert matrix to sparse matrix#####
# https://stackoverflow.com/questions/10555210/r-convert-matrix-or-data-frame-to-sparsematrix
exp <- Matrix(as.matrix(exp),sparse = T)
exp[1:4,1:4]
# 4 x 4 sparse Matrix of class "dgCMatrix"
#               AAACATACATTTCC.1 AAACATACCAGAAA.1 AAACATACCATGCA.1
# AL627309.1                   .                .                .
# RP11-206L10.2                .                .                .
# LINC00115                    .                .                .
# NOC2L                        .                .                .
#               AAACATACCTCGCT.1
# AL627309.1                   .
# RP11-206L10.2                .
# LINC00115                    .
# NOC2L                        .

sce<-SingleCellExperiment(assays = list(counts = exp))
Test_obj <-new("SingCellaR",sce)
Test_obj
# An object of class SingCellaR with a matrix of : 14045 genes across 24532 samples.
process_cells_annotation(Test_obj,mito_genes_start_with="MT-")
...
```

**Comment by supatt-lab** [comment]
This is great!. Thanks for sharing the codes!.

**Comment by TatjanaUffelmann** [comment]
Hi, 

I am trying to convert my my SingleCellExperiment to SingCellaR object. 
Hereby I first extract the matrix from my sce object and then create a new SingleCellExperiment and as next the SingCellaR object. However my meta data is empty afterwards and I can not do anything. 

What do I do wrong? Your help will be very much appreciated. 
Thanks a lot

mat <- assays(sce)[['counts']]       (output mat = 32285 x 169479 sparse Matrix of class "dgCMatrix")
sce<-SingleCellExperiment(assays = list(counts = mat))
Test_obj <-new("SingCellaR",sce)   (output = An object of class SingCellaR with a matrix of : 32285 genes across 169479 samples.)

Test_obj@meta.data
Object of class "data.frame"
data frame with 0 columns and 0 rows

**Comment by supatt-lab** [comment]
Hi,
Sorry for my slow reply. Please see below. You have to run the
"process_cells_annotation" function.
Hope this helps!
Best,
Supat


> library(SingleCellExperiment)
> library(SingCellaR)
>
> my_obj<-local(get(load("Psaila_et_al.rdata")))
> ***@***.***$counts
> sce<-SingleCellExperiment(assays = list(counts = my.umi))
> Test_obj <-new("SingCellaR",sce)
> Test_obj
An object of class SingCellaR with a matrix of : 33538 genes across 122154
samples.
> ***@***.***
Object of class "data.frame"
data frame with 0 columns and 0 rows
> process_cells_annotation(Test_obj)
[1] "List of mitochondrial genes:"
 [1] "MT-ND1"  "MT-ND2"  "MT-CO1"  "MT-CO2"  "MT-ATP8" "MT-ATP6" "MT-CO3"
 "MT-ND3"  "MT-ND4L"
[10] "MT-ND4"  "MT-ND5"  "MT-ND6"  "MT-CYB"
[1] "The meta data is processed."
> ***@***.***)
                      Cell sampleID UMI_count detectedGenesPerCell
percent_mito
1 AAACCCAGTCCCGCAA-1_HD_01  1_HD_01     30945                 5277
5.286799
2 AAACCCATCACCTCAC-1_HD_01  1_HD_01     12030                 3108
1.562760
3 AAACCCATCCGTGACG-1_HD_01  1_HD_01      7162                 2356
1.061156
4 AAACGAACAATCGTCA-1_HD_01  1_HD_01     15549                 3274
2.649688
5 AAACGAACACTGGCCA-1_HD_01  1_HD_01     22794                 4139
4.505572
6 AAACGAACACTTTATC-1_HD_01  1_HD_01     18205                 3659
5.256798
>
