### ISSUE TITLE
Changing cluster labels without import 

### ISSUE THREAD

**Issue by LacquerHed** [supatt-lab/SingCellaR#20]
Pretty basic question and I may have missed it in the tutorial, but how do you change cluster labels in the metadata outside of importing them as the tutorial shows or via integration with something like Seurat? Thanks.

**Comment by supatt-lab** [comment]
Hi,

Apologies for my slow reply; I am not sure i got your problem.  
But you can simply add the metadata to the SingCellaR's object as described below:

my_meta<-SingCellaR_object@meta.data
my_meta.update<-merge(my_meta,"your_metadata_from_Seurat's_object",all.x=T)
SingCellaR_object@meta.data<-my_meta.update

###now you can simply plot UMAP labeled by whatever features in your new metadata###
plot_umap_label_by_a_feature_of_interest(my_obj,feature=“your_feature_of_interest_found_in_the_updated_metadata”)

Hope this helps!

Best,
Supat
