### ISSUE TITLE
Error: "SingCellaR_Int” is not a defined class

### ISSUE THREAD

**Issue by Manoswini-02** [supatt-lab/SingCellaR#21]
Hi

I am trying to use SingCellaR and preprocessed individual samples. When I am trying to integrate biological controls it throws me the error :

Error in getClass(Class, where = topenv(parent.frame())) : 
  “SingCellaR_Int” is not a defined class
In addition: Warning messages:
1: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
2: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
3: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
4: In doTryCatch(return(expr), name, parentenv, handler) :
  display list redraw incomplete
5: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state
6: In doTryCatch(return(expr), name, parentenv, handler) :
  invalid graphics state

Any insights why this error occurred?

Manoswini

**Comment by supatt-lab** [comment]
Please see how to fix this problem from the closed issue https://github.com/supatt-lab/SingCellaR/issues/12

Thank you
