### ISSUE TITLE
caught segfault

### ISSUE THREAD

**Issue by FionaMoon** [supatt-lab/SingCellaR#3]
Hi,
  I got problem with code `runPCA(PBMCs, use.components=12, use.regressout.data = T)` no matter what parameter I choose.
The object is less than 3GB , I couldn't understand why memory is not enough.

>  *** caught segfault ***
address 0x10, cause 'memory not mapped'
Traceback:
 1: CGetNrow(x@address)
 2: nrow(x)
 3: nrow(x)
 4: dim(x)
 5: dim(x)
 6: FUN(X[[i]], ...)
 7: lapply(X = X, FUN = FUN, ...)
 8: sapply(x, nrow)
 9: nodes.RowLinkedMatrix(x)
10: nodes(x)
11: rownames.RowLinkedMatrix(x)
12: dimnames.RowLinkedMatrix(x)
13: dimnames(x)
14: rownames(my.select.data)
15: rownames(my.select.data) %in% rownames(selected.genes)
16: my.select.data[rownames(my.select.data) %in% rownames(selected.genes),     as.character(cells.used$Cell)]
17: runPCA(PBMCs, use.components = 12, use.regressout.data = T)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: 

Thank you in advance.
Fiona

**Comment by FionaMoon** [comment]
I've already save this problem by re-install this package.

**Comment by supatt-lab** [comment]
Thanks for letting me know. Great that you could solve the problem by
re-install the package!.
