### ISSUE TITLE
Bugs of GSEA Function

### ISSUE THREAD

**Issue by FionaMoon** [supatt-lab/SingCellaR#4]
Hi,
I found another problem when run the pbmc 3k sample of 10x. 
You can get pbmc3k as following
```
library(scater)
library(Seurat)
# install SeuratDisk from GitHub using the remotes package remotes::install_github(repo =
# 'mojaveazure/seurat-disk', ref = 'develop')
library(SeuratDisk)
library(SeuratData)
library(patchwork)
# download and save PBMC3K from SeuratData
InstallData("pbmc3k")
pbmc <- LoadData(ds = "pbmc3k", type = "pbmc3k.final")
```
Then ,I run code as the vignette.
```
pre_rankedGenes_for_GSEA <- read_rds("./SingCellaR_example_datasets/10x_genomics_5K_PBMCs/PBMCs_preRankedGenes_for_GSEA.rds")

fgsea_Results <- Run_fGSEA_for_multiple_comparisons(GSEAPrerankedGenes_list = pre_rankedGenes_for_GSEA,
gmt.file = "./SingCellaR_example_datasets/Human_genesets/human.hematopoiesis.signature.genes.gmt", eps = 0)
```
 If I set `eps = 0` , the program will run forever without warning.
When I use default value of `eps`, the `NES` of cluster NK-cell will be zero.
I also ask the author of fgsea (a package build-in SingCellaR), but I'm not sure where the problem is.
# https://github.com/ctlab/fgsea/issues/112

Fiona

**Comment by supatt-lab** [comment]
Hi Fiona,
I am not sure why you get this problem. Please try to follow the scripts below to see if you still get the problem.
I run it without any problem.

I hope this helps!
Supat


library(Seurat)
library(SingCellaR)
library(SingleCellExperiment)

##Download Seurat data from http://seurat.nygenome.org/src/contrib/pbmc3k.SeuratData_3.1.4.tar.gz
##Load file pbmc3k.final.rda into R

load(file="pbmc3k.SeuratData/data/pbmc3k.final.rda")
mat<-pbmc3k.final@assays$RNA@counts
sce<-SingleCellExperiment(assays = list(counts = mat))
PBMCs<-new("SingCellaR", sce)

process_cells_annotation(PBMCs, mito_genes_start_with = "MT-")
plot_cells_annotation(PBMCs,type="histogram")
plot_cells_annotation(PBMCs,type="boxplot")
plot_UMIs_vs_Detected_genes(PBMCs)

DoubletDetection_with_scrublet(PBMCs)
filter_cells_and_genes(PBMCs,
                       min_UMIs=500,
                       max_UMIs=8000,
                       min_detected_genes=300,
                       max_detected_genes=2500,
                       max_percent_mito=5,
                       genes_with_expressing_cells = 10)

normalize_UMIs(PBMCs,use.scaled.factor = T)
remove_unwanted_confounders(PBMCs,residualModelFormulaStr="~UMI_count+percent_mito")
get_variable_genes_by_fitting_GLM_model(PBMCs,mean_expr_cutoff = 0.1,disp_zscore_cutoff = 0.05)
remove_unwanted_genes_from_variable_gene_set(PBMCs,gmt.file = "../SingCellaR_example_datasets//Human_genesets/human.ribosomal-mitocondrial.genes.gmt",
                                             removed_gene_sets=c("Ribosomal_gene","Mitocondrial_gene"))
plot_variable_genes(PBMCs)
runPCA(PBMCs,use.components=30,use.regressout.data = T)
plot_PCA_Elbowplot(PBMCs)
runUMAP(PBMCs,dim_reduction_method = "pca",n.dims.use = 10,n.neighbors = 20,
       uwot.metric = "euclidean")

identifyClusters(PBMCs,n.dims.use = 10,n.neighbors = 20,knn.metric = "euclidean")
plot_umap_label_by_clusters(PBMCs,show_method = "louvain",point.size = 1)

pre_rankedGenes_for_GSEA<-identifyGSEAPrerankedGenes_for_all_clusters(PBMCs,
                                                                      cluster.type = "louvain")

fgsea_Results_Test<-Run_fGSEA_for_multiple_comparisons(GSEAPrerankedGenes_list = pre_rankedGenes_for_GSEA,
                                                  eps = 0,
                                                  gmt.file = "../SingCellaR_example_datasets/Human_genesets/human.hematopoiesis.signature.genes.gmt")

plot_heatmap_for_fGSEA_all_clusters(fgsea_Results_Test,isApplyCutoff = TRUE,
                                    use_pvalues_for_clustering=T,
                                    show_NES_score = T,fontsize_row = 5,
                                    adjusted_pval = 0.10,
                                    show_only_NES_positive_score = T,format.digits = 3,
                                    clustering_method = "ward.D",
                                    clustering_distance_rows = "euclidean",
                                    clustering_distance_cols = "euclidean",show_text_for_ns = F)

**Comment by FionaMoon** [comment]
Thank you for you help , Supat !
I think the error caused by other algorithm. Because I didn't run `get_variable_genes_by_fitting_GLM_model` . 
I use other packages to calculate different expression genes instead . Then I input the result (which cantains pval and Lg2FC )into `Run_fGSEA_for_multiple_comparisons`.
There were no problem when I run the full workflow of SingCellaR.
