### ISSUE TITLE
Issue with doublet filtering

### ISSUE THREAD

**Issue by BeepBoop312** [supatt-lab/SingCellaR#6]
Hi, I'm unable to perform doublet filtering on the singcellar object using scrublet. There seems to be an issue with installing scrublet using py_install. fa2 and and networkx installation works, but scrublet doesn't.

**Comment by supatt-lab** [comment]
Hi,

Would you try to follow the instruction described in https://star-protocols.cell.com/protocols/1530#step-by-step-method-details. Below should work, if not please see the instruction from https://github.com/swolock/scrublet
 
> library(reticulate)
> conda_create("r-reticulate", python_version="3.8")
> py_install("fa2", envname="r-reticulate")
> py_install("networkx", envname="r-reticulate”)
> py_install("Scrublet",envname="r-reticulate")

Hope this helps!
Best,
Supat

**Comment by BeepBoop312** [comment]
I figured out the issue! Turns out conda_install should be used instead of py_install.

**Comment by wenweixiong** [comment]
Hello, 

I have managed to install Scrublet for SingCellaR from my side (steps attached) and thought I'd share the steps here in case helpful for you and others. 

Though I'm certain there's more than one way to do this!

Sean
[Scrublet Installation.pptx](https://github.com/supatt-lab/SingCellaR/files/9021805/Scrublet.Installation.pptx)
