### ISSUE TITLE
Issue with remove_unwanted_genes_from_variable_gene_set function

### ISSUE THREAD

**Issue by BeepBoop312** [supatt-lab/SingCellaR#8]
Hello, 
The remove_unwanted_genes_from_variable_gene_set function does not seem to work for me. I always receive the error "1 input gene names do not present in the GMT file" even when using the provided testing GMT file. Any help would be greatly appreciated. Thanks!

**Comment by supatt-lab** [comment]
Hi,

Sorry for my slow reply.
Not sure if you still see the error. I would guess this is not the error but the warning that you can continue running the pipeline. I do not see this problem when I use the latest version of SingCellaR (version 1.2.1). 
Please see the instruction here https://supatt-lab.github.io/SingCellaR.Doc/.

Best,
Supat
